name: Create Issues from TODOs

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Grant permissions to create issues
permissions:
  contents: read
  issues: write

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create GitHub issues from TODOs
        run: bun run create-issues
        env:
          GH_TOKEN: ${{ github.token }}
